name: PTI-LDM-VAE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - albumentations==2.0.8
    - matplotlib==3.10.6
    - monai==1.5.1
    - numpy==2.3.3
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - pandas==2.3.2
    - Pillow==11.3.0
    - PyYAML==6.0.3
    - scikit-learn==1.7.2
    - scipy==1.16.2
    - scikit-image==0.24.0
    - tensorflow==2.20.0
    - tifffile==2024.9.20
    - torch==2.5.1
    - torchsummary==1.5.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - umap==0.1.1